package client;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.net.Socket;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class processRunning extends javax.swing.JFrame {
    
    public Vector<String> datas = new Vector();
    public String appStart = null;
    @Override
    public void list(){
        connectClient a = new connectClient();
        try {
            ObjectInputStream ois = new ObjectInputStream(a.connect().getInputStream());
            Object ob = ois.readObject();
            datas = (Vector<String>) ob;
        } catch (IOException ex) {
            Logger.getLogger(processRunning.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(processRunning.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    /**
     * Creates new form processRunning
     */
    public processRunning() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kill = new javax.swing.JButton();
        xoa = new javax.swing.JButton();
        xem = new javax.swing.JButton();
        start = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kill.setText("Kill");
        kill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                killActionPerformed(evt);
            }
        });

        xoa.setText("Xóa");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });

        xem.setText("Xem");
        xem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemActionPerformed(evt);
            }
        });

        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name Process", "ID Process", "User Name", "CPU"
            }
        ));
        jScrollPane1.setViewportView(list);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kill, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(xem, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kill, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemActionPerformed
        requestServer r = new requestServer();
        r.request("xemProcess");
        list();
        
        System.out.print(datas.get(0));
        
        String data[][] = new String[datas.size()][100];
        String saveRow[][] = new String[datas.size()][100];

        for (int j = 3; j < datas.size(); j++) {
            String str = datas.get(j);
            String[] arrOfStr = str.split(" ");
            for (int i = 0; i < arrOfStr.length; i++) {
                if (arrOfStr[i].length() != 0) {
                    data[j][i] = arrOfStr[i];
                }
            }
        }
        
        int index = 0;
        for (int i = 3; i < datas.size(); i++) {
            int k = 0;
            for (int j = 0; j < data[i].length; j++) {  
                if(data[i][j] != null){
                    saveRow[index][k] = data[i][j];
                    k++;
                }
            }
            index ++;
        }
        String cols[] = {"Name Process", "ID Process", "User Name", "CPU"};
        DefaultTableModel model = new DefaultTableModel(saveRow, cols);
        list.setModel(model);
    }//GEN-LAST:event_xemActionPerformed

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        String cols[] = {"Name Process", "ID Process", "User Name", "CPU"};
        String saveRow[][] = new String[0][0];
        DefaultTableModel model = new DefaultTableModel(saveRow, cols);
        list.setModel(model);
    }//GEN-LAST:event_xoaActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
           new Start().setVisible(true);
        });
    }//GEN-LAST:event_startActionPerformed

    private void killActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_killActionPerformed
      
        java.awt.EventQueue.invokeLater(() -> {
            new kill().setVisible(true);
        });
    
    }//GEN-LAST:event_killActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kill;
    private javax.swing.JTable list;
    private javax.swing.JButton start;
    private javax.swing.JButton xem;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables
}
